Algoritmo "03"
// Crie um programa que leia o nome e o salário de um funcionário, mostrando no
//final uma mensagem.
//Ex:
//Nome do Funcionário: Maria do Carmo
//Salário: 1850,45
//O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.
Var
nome: caractere
sal:real


Inicio
EscrevaL("Nome do Funcionário: ")
Leia(nome)
EscrevaL("Salário: ")
Leia(sal)
Escreva("O funcionário ", nome," tem um salário de R$", sal)


Fimalgoritmo