Algoritmo "07"
// Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
//sua terça parte.
//Ex:
//Digite um número: 3.5
//O dobro de 3.5 é 7.0
//A terça parte de 3.5 é 1.16666
Var
num,dob,ter:real


Inicio
EscrevaL("Escreva um número: ")
Leia(num)
dob <- num * 2
ter <- num / 3
EscrevaL("O dobro de ", num," é: ",dob)
EscrevaL("A terça parte de ", num," é :", ter:4:2)


Fimalgoritmo